name: redu-binder
channels:
  - astropy
dependencies:
- astropy=1.2.1
- matplotlib
- ipython
- jupyter
- ipywidgets=4*
- scipy
- nose
- mock
- funcsigs
- pillow
- ccdproc=1*
- scikit-image
- dask
- pip:
  - msumastro==0.9.0
  - reducer==0.3.0

