name: redu-binder
dependencies:
- astropy=1.0.4=np19py27_0
- certifi=14.05.14=py27_0
- decorator=4.0.4=py27_0
- freetype=2.5.2=2
- funcsigs=0.4=py27_0
- ipykernel=4.0.3=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.0.3=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=1
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=4.0.0=py27_0
- jupyter_console=4.0.2=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libtiff=4.0.2=1
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_3
- mistune=0.7.1=py27_0
- mock=1.3.0=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.0=py27_0
- nose=1.3.7=py27_0
- notebook=4.0.5=py27_0
- numpy=1.9.3=py27_0
- openssl=1.0.1k=1
- path.py=8.1.2=py27_0
- pbr=1.3.0=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pillow=3.0.0=py27_0
- pip=7.1.2=py27_0
- ptyprocess=0.4=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.3=py27_0
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.6=py27_0
- pyzmq=14.7.0=py27_0
- qt=4.8.6=3
- qtconsole=4.0.1=py27_0
- readline=6.2=2
- scipy=0.16.0=np19py27_1
- setuptools=18.3.2=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.5=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.2.1=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - ccdproc==0.3.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.0.0
  - jupyter-console==4.0.2
  - jupyter-core==4.0.6
  - jupyter-pip==0.3
  - msumastro==0.8.5
  - reducer==0.2.1

