name: redu-binder
channels:
  - astropy
  - conda-forge
dependencies:
- python=3
- astropy>=2
- matplotlib
- ipython
- jupyter
- ipywidgets=7*
- scipy
- nose
- mock
- funcsigs
- pillow
- ccdproc
- scikit-image
- dask
- pip:
  - msumastro==0.9.5
  - reducer==0.4.0

